---
title: TELUK LAMONG CARGO DISTRIBUTION CENTER
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    is_post: true
    layout: post
    tags:
    - teluk lamong
    - terminal cargo
    - surabaya
name: TELUK LAMONG CARGO DISTRIBUTION CENTER
description: We are TELUK LAMONG CARGO DISTRIBUTION CENTER located in East Java, Indonesia,
  we provide warehousing rent, best location for your logistic business.
avatar: 
paginate: 5
footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: 
  instagram: 
  linkedin: 
  pinterest: 
  rss: 
  twitter: 
  stackoverflow: 
  youtube: 
  googleplus: 
disqus: 
google_analytics: 
url: http://www.teluklamongcargo.co.id
baseurl: ''
permalink: "/:title/"
excerpt_separator: "<!--more-->"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :expanded
gems:
- jekyll-sitemap
- jekyll-feed
- jekyll-redirect-from
- jekyll-seo-tag
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
